# Generated by Django 3.0.6 on 2020-06-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcasestep',
            name='webcasename',
        ),
    ]
