# Generated by Django 3.0.7 on 2020-06-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apistep',
            name='apistep',
        ),
    ]
