# Generated by Django 3.0.7 on 2020-06-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_remove_apistep_apistep'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistep',
            name='apistep',
            field=models.CharField(max_length=100, null=True, verbose_name='测试步骤'),
        ),
    ]
